bgc:        "{{ colors.background }}"
fgc:        "{{ colors.foreground }}"
csc:        "{{ colors.cursor }}"

n_black:    "{{ colors.black.normal }}"
b_black:    "{{ colors.black.bold }}"
n_red:      "{{ colors.red.normal }}"
b_red:      "{{ colors.red.bold }}"
n_green:    "{{ colors.green.normal }}"
b_green:    "{{ colors.green.bold }}"
n_yellow:   "{{ colors.yellow.normal }}"
b_yellow:   "{{ colors.yellow.bold }}"
n_blue:     "{{ colors.blue.normal }}"
b_blue:     "{{ colors.blue.bold }}"
n_magenta:  "{{ colors.magenta.normal }}"
b_magenta:  "{{ colors.magenta.bold }}"
n_cyan:     "{{ colors.cyan.normal }}"
b_cyan:     "{{ colors.cyan.bold }}"
n_white:    "{{ colors.white.normal }}"
b_white:    "{{ colors.white.bold }}"
